#!/usr/bin/env bash
# configuring the subdomains
func () {
	output=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1)
	echo "$2 $output" | awk '{print "The subdomain "$1" is a "$5" record and points to "$6""}'
}
if [ -z "$2" ]
then
	func "$1" "www"
	func "$1" "lb-01"
	func "$1" "web-01"
	func "$1" "web-02"
else
	func "$1" "$2"
fi
