#!/usr/bin/env bash
# configure an ubuntu nginx
server {
   listen 80;
   listen [::]:80;
   #server_name example.com;
   index index.html index.htm index.nginx-debian.html;
   root /var/www/html
   #location / {
              #try_files $uri $uri/ =404;
   #}
}
