#!/usr/bin/env bash
# configuring nginx server for redirect
sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/redirect_me
printf %s "server {
     listen 80;
     listen [::]:80;
     root /var/www/html
     server_name /redirect_me
     return 301 https://www.youtube.com$request_uri;
}" > /etc/nginx/sites-available/default
sudo service nginx start
