#!/usr/bin/env bash
# configure an ubuntu nginx
sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/404_page.html
echo "Ceci n'est pas une page" > /var/www/html/404_page.html
printf %s "server {
   listen 80;
   listen [::]:80;
   root /var/www/html;
   index index.html index.htm;
   error_page 404 /404_page.html;
}" > /etc/nginx/sites-available/default
sudo service nginx restart
