#!/usr/bin/env bash
# double the number of server
sudo apt-get update
sudo apt-get -y install nginx
# touch /var/www/html/redirect_me
printf %s "server {
     listen 80;
     listen [::]:80;
     root /var/www/html;
     index index.html index.htm;
     add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default
sudo service nginx restart
