#!/usr/bin/env bash
# create a script and kill a process

echo $$>"/var/run/myscript.pid"
#echo "To infinity and beyond"
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid; exit 0" SIGQUIT
while true
do
	echo "To infinity and beyond"
done
