#!/usr/bin/env bash
# initializing manage my process

if [ "$1" = "start" ]
then
	source manage_my_process &
	echo $$>"/var/run/my_process.pid"
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	pkill -f "manage_my_process"
	#kill "$(pgrep -f /manage_my_process)"
	rm "/var/run/my_process.pid"
	echo "manage_my_process stopped"
	#pkill -f "manage_my_process"
elif [ "$1" == "restart" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm "/var/run/my_process.pid"
	source manage_my_process &
	echo $$>"/var/run/my_process.pid"
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

