#!/usr/bin/env bash
# displays the hour amd minutes of clock

i=1
j=1
while ((i<=12))
do
	while ((j<60))
	do
		if ((j == 1))
		then
			echo "Hour: 0"
		fi
		echo "$j"
		((j++))
	done
	if ((i == 1))
	then
		echo "Hour: 1"
	fi
	echo "$i"
	((i++))
done
