#!/usr/bin/env bash
# displays the hour amd minutes of clock

i=1
j=1
h=0
while ((i<=12))
do
	while ((j<60))
	do
		if ((j == 59))
		then
			((h++))
		fi
		if ((j == 1))
		then
			echo "Hour: $h"
		fi
		echo "$j"
		((j++))
	done
	if ((i == 1))
	then
		echo "Hour: $h"
	fi
	if ((i == 12))
	then
		echo "0"
		break
	fi
	echo "$i"
	((i++))
done
