#!/usr/bin/env bash
# configure an ubuntu nginx to proxy requests to process on port 5000
# sudo apt-get update
# sudo apt-get -y install nginx
# touch /var/www/html/index.html
# echo "Hello World!" > /var/www/html/index.html
printf %s "server {
   listen 80;
   listen [::]:80;
   root /var/www/html;
   index index.html index.htm;
   location /airbnb-onepage/ {
         proxy_pass http://localhost:5000;
   }
}" > etc/nginx/sites-enabled/default
sudo service nginx start
