#!/usr/bin/env bash
# configure nginx to serve proxy request
server {
     listen 80;
     listen [::]:80;
     root /var/www/html;
     index index.html index.htm;
     add_header X-Served-By 142632-web-01;
     location /airbnb-onepage/ {
         proxy_pass http://localhost:5000;
     }
}
server {
     listen 80;
     listen [::]:80;
     root /var/www/html;
     index index.html index.htm;
     add_header X-Served-By 142632-web-01;
     location /airbnb-dynamic/number_odd_or_even/(\d+)$ {
         proxy_pass http://localhost:5001/airbnb-dynamic/$1;
     }
}
